# Generated by Django 4.0.4 on 2022-04-22 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinkFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(default='0.0.0.0', verbose_name='Ip адрес')),
                ('user_agent', models.TextField(default=None, null=True, verbose_name='User-agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время перехода')),
            ],
            options={
                'verbose_name': 'Переход по ссылке',
                'verbose_name_plural': 'Переходы по ссылкам',
            },
        ),
        migrations.CreateModel(
            name='SourceLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_link', models.CharField(max_length=16, unique=True, verbose_name='slug')),
                ('forward_link', models.URLField(max_length=255, verbose_name='forward_link')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.CharField(blank=True, max_length=128, null=True, verbose_name='Сессия')),
            ],
            options={
                'verbose_name': 'Ссылочная пара',
                'verbose_name_plural': 'Ссылочные пары',
            },
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=32, verbose_name='Telegram id')),
                ('username', models.CharField(max_length=128, verbose_name='Username')),
                ('first_name', models.CharField(max_length=32, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=32, verbose_name='Фамилия')),
                ('short_links', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tg_user', to='core.sourcelink')),
            ],
            options={
                'verbose_name': 'Пользователь Telegram',
                'verbose_name_plural': 'Пользователи Telegram',
            },
        ),
        migrations.AddIndex(
            model_name='sourcelink',
            index=models.Index(fields=['id'], name='core_source_id_71ca90_idx'),
        ),
        migrations.AddField(
            model_name='linkfollow',
            name='link_pair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='core.sourcelink'),
        ),
        migrations.AddIndex(
            model_name='telegramuser',
            index=models.Index(fields=['external_id'], name='core_telegr_externa_92ab85_idx'),
        ),
    ]
