# Generated by Django 4.0.4 on 2022-04-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_generalpreferences'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=128, verbose_name='Ссылка')),
                ('title', models.CharField(max_length=128, verbose_name='Тег Title')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
            },
        ),
        migrations.DeleteModel(
            name='GeneralPreferences',
        ),
    ]
