# Generated by Django 4.0.4 on 2022-04-26 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_page_delete_generalpreferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
