# Generated by Django 4.0.4 on 2022-04-27 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_page_modified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='description',
            field=models.CharField(default='', max_length=255, verbose_name='Тег description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='headline_h1',
            field=models.CharField(default='', max_length=64, verbose_name='Заголовок h1'),
            preserve_default=False,
        ),
    ]
