# Generated by Django 4.0.4 on 2022-04-27 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_page_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='description',
            field=models.TextField(max_length=255, null=True, verbose_name='Тег description'),
        ),
        migrations.AlterField(
            model_name='page',
            name='headline_h1',
            field=models.CharField(max_length=64, null=True, verbose_name='Заголовок h1'),
        ),
    ]
